Reporting

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -4,8 +4,11 @@
 # automake        >= 1.9
 # libtool         >= 1.4
 glibtoolize -f 2>/dev/null || libtoolize -f
-aclocal -I ./config \
-&& autoheader \
-&& automake --foreign --add-missing --copy \
-&& autoconf
+if aclocal -I config && autoheader && automake --foreign --add-missing --copy && autoconf 
+then
+        echo "Success" 
+else
+        echo "Bootstrapping Build System failed"
+        exit 1
+fi
 
